# Nixpacks configuration file

[phases.setup]
nixPkgs = ['docker']
aptPkgs = ['curl', 'wget', 'docker.io']

[phases.start]
commands = [
  "docker compose -f docker-compose/full-service-compose.yml up --build"
]