global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
  scrape_timeout: 10s
  evaluation_interval: 30s # Evaluate rules every 30 seconds. The default is every 1 minute.

# add alertmanager. Remove this if you don't need alerts
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

# can be removed if alertmanager is not used
rule_files:
  - 'alerts/*.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: ecoflow-exporter
    static_configs:
      - targets:
          - go_ecoflow_exporter:2112

