{
 "title": "EcoFlow",
 "description": "EcoFlow dashboard",
 "tags": [
  "ecoflow",
  "prometheus",
  "electricity",
  "IoT"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ecoflow_online, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_online{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_vol{device=\"$device\"} or ecoflow_inv_inv_in_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter IN Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_amp{device=\"$device\"} or ecoflow_inv_inv_in_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Charging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_ems_chg_remain_time{device=\"$device\"} or ecoflow_bms_ems_status_chg_remain_time{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Full Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_full_cap{device=\"$device\"} or ecoflow_bms_bms_status_full_cap{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "BMS Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(ecoflow_bms_master_amp{device=\"$device\"}) or abs(ecoflow_bms_bms_status_amp{device=\"$device\"})"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol{device=\"$device\"} or ecoflow_bms_bms_status_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MIN Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MAX Cell Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_f32_show_soc{device=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{device=\"$device\"} or ecoflow_bms_master_soc{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Watts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_output_watts{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Volts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_vol{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter OUT Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_inv_out_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Discharging Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_ems_dsg_remain_time{device=\"$device\"} or ecoflow_bms_ems_status_dsg_remain_time{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Remain Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_remain_cap{device=\"$device\"} or ecoflow_bms_bms_status_remain_cap{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Cycles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_cycles{device=\"$device\"} or ecoflow_bms_bms_status_cycles{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_inv_out_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MIN Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_min_cell_temp{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MAX Cell Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_max_cell_temp{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_amp{device=\"$device\"} or ecoflow_bms_bms_status_amp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_soc{device=\"$device\"} or ecoflow_bms_bms_status_f32_show_soc{device=\"$device\"}",
     "legendFormat": "Battery Level"
    }
   ]
  },
  {
   "title": "I/O Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_input_watts{device=\"$device\"}",
     "legendFormat": "Input Watts"
    },
    {
     "expr": "ecoflow_inv_output_watts{device=\"$device\"}",
     "legendFormat": "Output Watts"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "abs(ecoflow_ems_chg_remain_time{device=\"$device\"}) or abs(ecoflow_bms_ems_status_chg_remain_time{device=\"$device\"}) ",
     "legendFormat": "Charging Remain Time"
    },
    {
     "expr": "abs(ecoflow_ems_dsg_remain_time{device=\"$device\"}) or abs(ecoflow_bms_ems_status_dsg_remain_time{device=\"$device\"})",
     "legendFormat": "Discharging Remain Time"
    }
   ]
  },
  {
   "title": "I/O Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_vol{device=\"$device\"} > 0",
     "legendFormat": "Inverter In"
    },
    {
     "expr": "ecoflow_inv_inv_out_vol{device=\"$device\"} > 0",
     "legendFormat": "Inverter Out"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ecoflow_inv_out_temp{device=\"$device\"} != 0",
     "legendFormat": "Inverter"
    },
    {
     "expr": "ecoflow_pd_car_temp{device=\"$device\"} != 0",
     "legendFormat": "PD Car"
    },
    {
     "expr": "ecoflow_bms_master_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_temp{device=\"$device\"} != 0",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_bms_master_max_cell_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_max_cell_temp{device=\"$device\"} != 0",
     "legendFormat": "Max Cell"
    },
    {
     "expr": "ecoflow_bms_master_min_cell_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_min_cell_temp{device=\"$device\"} != 0",
     "legendFormat": "Min Cell"
    },
    {
     "expr": "ecoflow_bms_master_max_mos_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_max_mos_temp{device=\"$device\"} != 0",
     "legendFormat": "Max MOS"
    },
    {
     "expr": "ecoflow_bms_master_min_mos_temp{device=\"$device\"} != 0 or ecoflow_bms_bms_status_min_mos_temp{device=\"$device\"} != 0",
     "legendFormat": "Min MOS"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "ecoflow_inv_ac_in_amp{device=\"$device\"}",
     "legendFormat": "AC IN Current"
    },
    {
     "expr": "ecoflow_inv_inv_out_amp{device=\"$device\"}",
     "legendFormat": "Inverter OUT Current"
    },
    {
     "expr": "abs(ecoflow_bms_bms_status_amp{device=\"$device\"})",
     "legendFormat": "BMS Current"
    }
   ]
  },
  {
   "title": "USB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ecoflow_pd_usb1_watts{device=\"$device\"}",
     "legendFormat": "USB"
    },
    {
     "expr": "ecoflow_pd_typec1_watts{device=\"$device\"}",
     "legendFormat": "TypeC"
    }
   ]
  },
  {
   "title": "Battery Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "ecoflow_bms_master_vol{device=\"$device\"} or ecoflow_bms_bms_status_vol{device=\"$device\"}",
     "legendFormat": "BMS"
    },
    {
     "expr": "ecoflow_bms_master_min_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_min_cell_vol{device=\"$device\"}",
     "legendFormat": "MIN Cell"
    },
    {
     "expr": "ecoflow_bms_master_max_cell_vol{device=\"$device\"} or ecoflow_bms_bms_status_max_cell_vol{device=\"$device\"}",
     "legendFormat": "MAX Cell"
    }
   ]
  },
  {
   "title": "MPPT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_watts/10", "legendFormat": "Watts in" },
      {
       "expr": "ecoflow_mppt_in_vol * ecoflow_mppt_in_amp / 1000",
       "legendFormat": "Watts on panel"
      }
     ]
    },
    {
     "title": "Solar voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_vol/10", "legendFormat": "Volts in" }
     ]
    },
    {
     "title": "Solar current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "ecoflow_mppt_in_amp/100", "legendFormat": "Amp in" }
     ]
    },
    {
     "title": "Battery Managemant System Power Balance ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      { "expr": "ecoflow_bms_master_amp/1000", "legendFormat": "Amp in" }
     ]
    },
    {
     "title": "Solar power",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[$__range]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[$__range]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[24h]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (24h)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[24h]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (24h)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[7d]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (7d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[7d]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (7d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_in_watts[30d]) / (count_over_time(ecoflow_mppt_in_watts[1m]) * 60) / 10",
       "legendFormat": "Battery charged (30d)"
      },
      {
       "expr": "sum_over_time(ecoflow_mppt_out_watts[30d]) / (count_over_time(ecoflow_mppt_out_watts[1m]) * 60) / 10",
       "legendFormat": "Collected (30d)"
      }
     ]
    },
    {
     "title": "Battery Energy Balance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ecoflow_bms_master_vol/1000 * ecoflow_bms_master_amp/1000",
       "legendFormat": "Master BMS"
      },
      {
       "expr": "ecoflow_mppt_in_vol * ecoflow_mppt_in_amp / 1000",
       "legendFormat": "Solar"
      }
     ]
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MQTT Messages Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "m/s" } },
   "targets": [
    {
     "expr": "rate(ecoflow_mqtt_messages_receive_total{device=\"$device\"}[1m])",
     "legendFormat": "MQTT Messages"
    }
   ]
  }
 ]
}